stages:
  - build
  - test

services:
  - docker:dind

test image:
  stage: test
  only:
    - deploy-test
  tags:
    - deploy-test
  script:
    - sudo docker-compose -f docker-compose-test.yml up -d --force-recreate --build
    - sudo docker image prune -f

build image:
  stage: build
  only:
    - deploy
  tags:
    - deploy    
    
  script:
    - sudo docker-compose up -d --force-recreate --build
    - sudo docker image prune -f